// src/hooks/useChatSessions.ts
import { useEffect } from "react";
import { useUIStore, ChatSession, ChatFolder } from "@/store/use-ui-store";

/**
 * Hook to initialize and manage chat sessions and folders
 * Provides mock data for development and testing
 */
export function useChatSessions() {
  const {
    sessions,
    folders,
    activeSessionId,
    setSessions,
    setFolders,
    setActiveSession,
  } = useUIStore();

  const initializeMockData = () => {
    // Create mock folders
    const mockFolders: ChatFolder[] = [
      {
        id: "folder-1",
        name: "Mobile App Refactor",
        created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "folder-2",
        name: "API Security Audit",
        created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "folder-3",
        name: "Backend Migration",
        created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "folder-4",
        name: "Documentation",
        created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "folder-5",
        name: "Research: LLM Tools",
        created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "folder-6",
        name: "DevOps Pipeline",
        created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ];

    // Create mock sessions
    const mockSessions: ChatSession[] = [
      // Sessions in folders
      {
        id: "session-1",
        title: "Refactor authentication module",
        folder_id: "folder-1",
        created_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Discussing authentication improvements...",
      },
      {
        id: "session-2",
        title: "UI component library setup",
        folder_id: "folder-1",
        created_at: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Setting up reusable components...",
      },
      {
        id: "session-3",
        title: "Navigation flow optimization",
        folder_id: "folder-1",
        created_at: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Improving user navigation experience...",
      },
      {
        id: "session-4",
        title: "JWT token validation",
        folder_id: "folder-2",
        created_at: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Reviewing JWT security implementation...",
      },
      {
        id: "session-5",
        title: "SQL injection prevention",
        folder_id: "folder-2",
        created_at: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Analyzing SQL injection vulnerabilities...",
      },
      {
        id: "session-6",
        title: "API rate limiting",
        folder_id: "folder-2",
        created_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Implementing rate limiting strategy...",
      },
      {
        id: "session-7",
        title: "CORS configuration",
        folder_id: "folder-2",
        created_at: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Setting up CORS policies...",
      },
      {
        id: "session-8",
        title: "OAuth2 implementation",
        folder_id: "folder-2",
        created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Implementing OAuth2 authentication...",
      },
      {
        id: "session-9",
        title: "Database schema migration",
        folder_id: "folder-3",
        created_at: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Planning database migration strategy...",
      },
      {
        id: "session-10",
        title: "Microservices architecture",
        folder_id: "folder-3",
        created_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 3.5 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Designing microservices structure...",
      },
      {
        id: "session-11",
        title: "API documentation",
        folder_id: "folder-4",
        created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Writing comprehensive API docs...",
      },
      {
        id: "session-12",
        title: "LLM integration research",
        folder_id: "folder-5",
        created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Researching LLM integration options...",
      },
      {
        id: "session-13",
        title: "Prompt engineering techniques",
        folder_id: "folder-5",
        created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 4.5 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Exploring prompt engineering best practices...",
      },
      {
        id: "session-14",
        title: "Model fine-tuning",
        folder_id: "folder-5",
        created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Fine-tuning models for specific tasks...",
      },
      {
        id: "session-15",
        title: "RAG system design",
        folder_id: "folder-5",
        created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 5.5 * 24 * 60 * 60 * 1000).toISOString(),
        preview: "Designing RAG system architecture...",
      },

      // History sessions (no folder) - 50+ items for lazy loading demo
      {
        id: "session-h1",
        title: "Fix ClickUp #402",
        folder_id: null,
        created_at: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString(),
        preview: "Resolving issue #402...",
      },
      {
        id: "session-h2",
        title: "Performance optimization",
        folder_id: null,
        created_at: new Date(Date.now() - 49 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 49 * 60 * 60 * 1000).toISOString(),
        preview: "Optimizing application performance...",
      },
      {
        id: "session-h3",
        title: "Bug fix: Login flow",
        folder_id: null,
        created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
        preview: "Fixing login flow issues...",
      },
      {
        id: "session-h4",
        title: "Code review: PR #156",
        folder_id: null,
        created_at: new Date(Date.now() - 47 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 47 * 60 * 60 * 1000).toISOString(),
        preview: "Reviewing pull request #156...",
      },
      {
        id: "session-h5",
        title: "Refactor Auth Flow",
        folder_id: null,
        created_at: new Date(Date.now() - 46 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 46 * 60 * 60 * 1000).toISOString(),
        preview: "Refactoring authentication flow...",
      },
      {
        id: "session-h6",
        title: "Database optimization",
        folder_id: null,
        created_at: new Date(Date.now() - 45 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 45 * 60 * 60 * 1000).toISOString(),
        preview: "Optimizing database queries...",
      },
      {
        id: "session-h7",
        title: "Frontend testing setup",
        folder_id: null,
        created_at: new Date(Date.now() - 44 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 44 * 60 * 60 * 1000).toISOString(),
        preview: "Setting up testing infrastructure...",
      },
      {
        id: "session-h8",
        title: "CI/CD pipeline review",
        folder_id: null,
        created_at: new Date(Date.now() - 43 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 43 * 60 * 60 * 1000).toISOString(),
        preview: "Reviewing CI/CD pipeline configuration...",
      },
      {
        id: "session-h9",
        title: "Cache implementation strategy",
        folder_id: null,
        created_at: new Date(Date.now() - 42 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 42 * 60 * 60 * 1000).toISOString(),
        preview: "Planning caching strategy for performance...",
      },
      {
        id: "session-h10",
        title: "Security audit findings",
        folder_id: null,
        created_at: new Date(Date.now() - 41 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 41 * 60 * 60 * 1000).toISOString(),
        preview: "Reviewing security audit results...",
      },
      {
        id: "session-h11",
        title: "Mobile app testing",
        folder_id: null,
        created_at: new Date(Date.now() - 40 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 40 * 60 * 60 * 1000).toISOString(),
        preview: "Testing mobile application features...",
      },
      {
        id: "session-h12",
        title: "API versioning strategy",
        folder_id: null,
        created_at: new Date(Date.now() - 39 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 39 * 60 * 60 * 1000).toISOString(),
        preview: "Planning API versioning approach...",
      },
      {
        id: "session-h13",
        title: "Error handling improvements",
        folder_id: null,
        created_at: new Date(Date.now() - 38 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 38 * 60 * 60 * 1000).toISOString(),
        preview: "Enhancing error handling mechanisms...",
      },
      {
        id: "session-h14",
        title: "Logging and monitoring setup",
        folder_id: null,
        created_at: new Date(Date.now() - 37 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 37 * 60 * 60 * 1000).toISOString(),
        preview: "Setting up logging and monitoring...",
      },
      {
        id: "session-h15",
        title: "User feedback analysis",
        folder_id: null,
        created_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
        preview: "Analyzing user feedback and suggestions...",
      },
      {
        id: "session-h16",
        title: "Feature flag implementation",
        folder_id: null,
        created_at: new Date(Date.now() - 35 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 35 * 60 * 60 * 1000).toISOString(),
        preview: "Implementing feature flags for rollout...",
      },
      {
        id: "session-h17",
        title: "Database indexing optimization",
        folder_id: null,
        created_at: new Date(Date.now() - 34 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 34 * 60 * 60 * 1000).toISOString(),
        preview: "Optimizing database indexes...",
      },
      {
        id: "session-h18",
        title: "Load testing and benchmarks",
        folder_id: null,
        created_at: new Date(Date.now() - 33 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 33 * 60 * 60 * 1000).toISOString(),
        preview: "Running load tests and benchmarks...",
      },
      {
        id: "session-h19",
        title: "Accessibility compliance check",
        folder_id: null,
        created_at: new Date(Date.now() - 32 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 32 * 60 * 60 * 1000).toISOString(),
        preview: "Checking accessibility compliance...",
      },
      {
        id: "session-h20",
        title: "SEO optimization review",
        folder_id: null,
        created_at: new Date(Date.now() - 31 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 31 * 60 * 60 * 1000).toISOString(),
        preview: "Reviewing SEO optimization strategies...",
      },
      {
        id: "session-h21",
        title: "Dependency update planning",
        folder_id: null,
        created_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
        preview: "Planning dependency updates...",
      },
      {
        id: "session-h22",
        title: "Code splitting strategy",
        folder_id: null,
        created_at: new Date(Date.now() - 29 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 29 * 60 * 60 * 1000).toISOString(),
        preview: "Planning code splitting for optimization...",
      },
      {
        id: "session-h23",
        title: "Bundle size analysis",
        folder_id: null,
        created_at: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
        preview: "Analyzing bundle size metrics...",
      },
      {
        id: "session-h24",
        title: "Memory leak investigation",
        folder_id: null,
        created_at: new Date(Date.now() - 27 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 27 * 60 * 60 * 1000).toISOString(),
        preview: "Investigating memory leak issues...",
      },
      {
        id: "session-h25",
        title: "WebSocket implementation",
        folder_id: null,
        created_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
        preview: "Implementing WebSocket communication...",
      },
      {
        id: "session-h26",
        title: "Real-time sync design",
        folder_id: null,
        created_at: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
        preview: "Designing real-time synchronization...",
      },
      {
        id: "session-h27",
        title: "Offline mode implementation",
        folder_id: null,
        created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        preview: "Implementing offline mode functionality...",
      },
      {
        id: "session-h28",
        title: "Data synchronization strategy",
        folder_id: null,
        created_at: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
        preview: "Planning data sync strategy...",
      },
      {
        id: "session-h29",
        title: "Conflict resolution mechanism",
        folder_id: null,
        created_at: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
        preview: "Implementing conflict resolution...",
      },
      {
        id: "session-h30",
        title: "State management refactor",
        folder_id: null,
        created_at: new Date(Date.now() - 21 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 21 * 60 * 60 * 1000).toISOString(),
        preview: "Refactoring state management system...",
      },
      {
        id: "session-h31",
        title: "Component library audit",
        folder_id: null,
        created_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
        preview: "Auditing component library...",
      },
      {
        id: "session-h32",
        title: "Design system documentation",
        folder_id: null,
        created_at: new Date(Date.now() - 19 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 19 * 60 * 60 * 1000).toISOString(),
        preview: "Documenting design system...",
      },
      {
        id: "session-h33",
        title: "Theming implementation",
        folder_id: null,
        created_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
        preview: "Implementing theming system...",
      },
      {
        id: "session-h34",
        title: "Dark mode support",
        folder_id: null,
        created_at: new Date(Date.now() - 17 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 17 * 60 * 60 * 1000).toISOString(),
        preview: "Adding dark mode support...",
      },
      {
        id: "session-h35",
        title: "Responsive design review",
        folder_id: null,
        created_at: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
        preview: "Reviewing responsive design...",
      },
      {
        id: "session-h36",
        title: "Mobile-first approach",
        folder_id: null,
        created_at: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
        preview: "Implementing mobile-first design...",
      },
      {
        id: "session-h37",
        title: "Touch interaction optimization",
        folder_id: null,
        created_at: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
        preview: "Optimizing touch interactions...",
      },
      {
        id: "session-h38",
        title: "Gesture recognition implementation",
        folder_id: null,
        created_at: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
        preview: "Implementing gesture recognition...",
      },
      {
        id: "session-h39",
        title: "Animation performance tuning",
        folder_id: null,
        created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        preview: "Tuning animation performance...",
      },
      {
        id: "session-h40",
        title: "Transition effects review",
        folder_id: null,
        created_at: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
        preview: "Reviewing transition effects...",
      },
      {
        id: "session-h41",
        title: "Micro-interactions design",
        folder_id: null,
        created_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
        preview: "Designing micro-interactions...",
      },
      {
        id: "session-h42",
        title: "User onboarding flow",
        folder_id: null,
        created_at: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
        preview: "Designing user onboarding...",
      },
      {
        id: "session-h43",
        title: "Tutorial content creation",
        folder_id: null,
        created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        preview: "Creating tutorial content...",
      },
      {
        id: "session-h44",
        title: "Help documentation update",
        folder_id: null,
        created_at: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
        preview: "Updating help documentation...",
      },
      {
        id: "session-h45",
        title: "FAQ section expansion",
        folder_id: null,
        created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        preview: "Expanding FAQ section...",
      },
      {
        id: "session-h46",
        title: "Knowledge base organization",
        folder_id: null,
        created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        preview: "Organizing knowledge base...",
      },
      {
        id: "session-h47",
        title: "Video tutorial production",
        folder_id: null,
        created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        preview: "Producing video tutorials...",
      },
      {
        id: "session-h48",
        title: "Community feedback integration",
        folder_id: null,
        created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        preview: "Integrating community feedback...",
      },
      {
        id: "session-h49",
        title: "Release notes preparation",
        folder_id: null,
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        preview: "Preparing release notes...",
      },
      {
        id: "session-h50",
        title: "Version 2.0 planning",
        folder_id: null,
        created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        preview: "Planning version 2.0 features...",
      },
    ];

    setFolders(mockFolders);
    setSessions(mockSessions);
    // Set the most recent history session as active
    setActiveSession("session-h8");
  };

  // Initialize with mock data on mount
  useEffect(() => {
    // Only initialize if empty
    if (sessions.length === 0 && folders.length === 0) {
      initializeMockData();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return {
    sessions,
    folders,
    activeSessionId,
  };
}
